### ISSUE TITLE
 code about robustness for noise frequency exp (Fig. 2b) 

### ISSUE THREAD

**Issue by DoyoungYoon** [xxxnell/how-do-vits-work#23]
안녕하세요. 저자님. 
우선 많은 인사이트를 주는 좋은 논문 감사드립니다.

저자님의 논문을 읽고 코드를 활용하여 여러 분석을 진행해 보고 있습니다.
그중에 저자님의 Fig. 2b의 robustness for noise frequency에 대한 분석을 진행해 보고자 합니다. 
그러나 코드에는 이 부분은 없는 것으로 보여 질문드리게 되었습니다. 

아마도 FreqAttack 클래스를 활용하는 것으로 보이는데,
혹시 이 실험을 재현해보기 위한 각 frequency별 random noise를 적용하는 실험 코드 공유를 해주실 수 있을까요?

감사드립니다.

**Comment by xxxnell** [comment]
Hi, @DoyoungYoon 

The code for Figure 2b was not released because it relies on the IN1K dataset. But my soon-to-be-published work also conducts this experiment, so I plan to publicly release the code (with dummy datasets). 

Anyway, please leave your email address in this thread or email (mailto:namuk.park@gmail.com) me, then I'll send you the snippets.

Thank you for your support and kind words.

**Comment by DoyoungYoon** [comment]
친절한 답변 감사합니다! 제 메일은 dbsehdudslaz@gmail.com 입니다. 좋은 연구 감사드립니다.
