### ISSUE TITLE
Frequency Analysis for MoCo-v3

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [xxxnell/how-do-vits-work#25]
Hi, thank you for your great work. We take you code to analysis the feature of MoCo-v3 from the frequency perspective, but we obtain the following trend:
![kl7gTzKilN](https://user-images.githubusercontent.com/30762564/201083840-493fcf3f-4bf2-4ff9-9c2c-314fb8b59a87.jpg)
I am a little bit confused, because I think there should be a decreasing trend.

**Comment by xxxnell** [comment]
Hi @YuanLiuuuuuu, thank you for reporting the great result. It may be intuitive that the high frequency amplitude of MoCo-v3 may be lower than that of other ViTs and some layers of MoCo-v3 reduce the high-frequency amplitude. Since I am also interested in the behaviours of self-supervised learning methods, could you please send me an e-mail (mailto:namuk.park@gmail.com) or leave your e-mail address here, if you don't mind? Then I'll try to follow up regarding this issue within a few weeks.
