### ISSUE TITLE
How do I implement Figure2(b) in detail?

### ISSUE THREAD

**Issue by pi-wo** [xxxnell/how-do-vits-work#43]
I have obtained the performance evaluation results of resnet and vit under different types of noise and different intensification using the robustness code you have given. But I do not know how the results of the effects of different frequencies of noise on the model performance in Figure2(b) are obtained. Can you share the specific code?

**Comment by xxxnell** [comment]
Hi @pi-wo,

Thank you for reaching out. Since Figure 2b depends on (ImageNet) datasets, I haven't uploaded the code. Please leave your email address or send a message to [namuk.park@gmail.com](mailto:namuk.park@gmail.com), and I'll send you the snippet for the experiment.

Hope you have a nice weekend!

**Comment by pi-wo** [comment]
Thank you for your reply to paper Figure2(b), which is of great help to my research. My email is dj2650898330@gmail.com.

Have a nice weekend.
